apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-slides
  namespace: workflow-slides
  labels:
    app: workflow-slides
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workflow-slides
  template:
    metadata:
      labels:
        app: workflow-slides
    spec:
      containers:
        - name: nginx
          image: ghcr.io/trevormil/workflow-slides:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: 10m
              memory: 24Mi
            limits:
              cpu: 100m
              memory: 64Mi
      imagePullSecrets:
        - name: ghcr-pull
