apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: workflow-slides
  namespace: workflow-slides
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts: [workflow.trevormil.com]
      secretName: workflow-trevormil-tls
  rules:
    - host: workflow.trevormil.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: workflow-slides
                port:
                  number: 80
