#!/usr/bin/env bash
# ci-watchdog — classify a failed CI run + auto-fix the trivial cases.
#
# Wired to fire on `pipeline.failed` webhooks (GitHub Action / GitLab job /
# local cron tail of `glab ci view`). The harness doesn't host a webhook
# receiver — the script does the real work, and any trigger can invoke it.
#
# Env vars expected:
#   CI_REPO_URL    — full repo URL (used for `cd` resolution + MR comment)
#   CI_PIPELINE_ID — pipeline / workflow run id
#   CI_MR_IID      — PR/MR number (for the comment + HITL link)
#   CI_BRANCH      — the MR's source branch (where to push the fix)
#   TERMINAL_REPO  — repo root (set by the harness when invoked)
#   TERMINAL_RUN_ID — run id (set by the harness)
#
# v0 allowlist: prettier-formatting only. Broaden one class at a time
# after a week of clean operation. Non-cheap classes route to HITL.

set -uo pipefail

: "${CI_PIPELINE_ID:?required}"
: "${CI_MR_IID:?required}"
: "${TERMINAL_REPO:?must be invoked via the harness}"

cd "$TERMINAL_REPO" || exit 1
forge=$(./.claude/bin/forge 2>/dev/null || echo "github")

# Dry-run mode: classify + log, but DON'T push. Toggle in
# ~/.config/TerMinal/ci-watchdog.json: { "dryRun": true }
dry_run=$(jq -r '.dryRun // true' ~/.config/TerMinal/ci-watchdog.json 2>/dev/null)
[ -z "$dry_run" ] && dry_run=true

# Pull the failed log
log_file=$(mktemp -t ci-log-XXXXXX)
trap 'rm -f "$log_file"' EXIT
if [ "$forge" = "github" ]; then
  gh run view "$CI_PIPELINE_ID" --log-failed > "$log_file" 2>&1 || \
    gh run view "$CI_PIPELINE_ID" --log > "$log_file" 2>&1
else
  glab ci view --log "$CI_PIPELINE_ID" > "$log_file" 2>&1
fi

# Per-MR fix cap — refuse runaway auto-fix loops
state_key="ci-watchdog-fixes-$CI_MR_IID"
fix_count=$(terminal-cli state get "$state_key" 2>/dev/null || echo "0")
fix_count=${fix_count:-0}
if [ "$fix_count" -ge 3 ]; then
  terminal-cli mcp file_hitl \
    title="CI watchdog · fix cap hit · MR !$CI_MR_IID" \
    action="Auto-fix already attempted $fix_count times. Investigate manually." \
    repo="$(basename "$TERMINAL_REPO")" \
    runId="${TERMINAL_RUN_ID:-}"
  exit 0
fi

# Deterministic classification via existing harness helper
classification=$(terminal-cli classify ci "$log_file")

echo "ci-watchdog: classification=$classification dry_run=$dry_run mr=!$CI_MR_IID"

# Record the would-be action for review (dry-run mode keeps this useful)
mkdir -p ~/.config/TerMinal/ci-watchdog-runs
cat > ~/.config/TerMinal/ci-watchdog-runs/"$(date +%s)-$CI_PIPELINE_ID.json" <<EOF
{
  "ts": $(date +%s)000,
  "pipelineId": "$CI_PIPELINE_ID",
  "mrIid": "$CI_MR_IID",
  "repo": "$(basename "$TERMINAL_REPO")",
  "branch": "${CI_BRANCH:-}",
  "classification": "$classification",
  "dryRun": $dry_run,
  "logFile": "$log_file"
}
EOF

# Route by class
case "$classification" in
  prettier-formatting)
    if [ "$dry_run" = "true" ]; then
      terminal-cli activity check \
        "CI watchdog (dry-run) · prettier · MR !$CI_MR_IID" \
        "would auto-fix prettier; toggle dryRun:false in ci-watchdog.json to enable"
      exit 0
    fi
    # Worktree-isolated codex run that ONLY fixes prettier formatting + pushes.
    wt="$HOME/CompSci/gauntlet/.worktrees/$(basename "$TERMINAL_REPO")/ci-fix-$CI_PIPELINE_ID"
    git worktree add -B "ci-fix/$CI_MR_IID-$CI_PIPELINE_ID" "$wt" "origin/${CI_BRANCH:-main}" 2>&1
    (
      cd "$wt"
      # Use bunx prettier directly — no LLM needed. If a project hasn't got
      # prettier in its deps, codex exec is the fallback path.
      if bunx prettier --write . 2>&1; then
        if git diff --quiet; then
          echo "no diff after prettier — nothing to fix"
        else
          git add -u
          git commit -m "chore: auto-fix prettier formatting

🤖 Generated by .agents/ci-watchdog.sh · pipeline $CI_PIPELINE_ID"
          git push origin "HEAD:${CI_BRANCH:-main}"
          if [ "$forge" = "github" ]; then
            gh pr comment "$CI_MR_IID" --body "🤖 Auto-fixed prettier formatting · pipeline #$CI_PIPELINE_ID"
          else
            glab mr note "$CI_MR_IID" -m "🤖 Auto-fixed prettier formatting · pipeline #$CI_PIPELINE_ID"
          fi
          terminal-cli activity check \
            "CI watchdog · auto-fixed prettier · MR !$CI_MR_IID" \
            "pushed fix commit; CI will re-run"
          terminal-cli state set "$state_key" "$((fix_count + 1))"
        fi
      else
        terminal-cli mcp file_hitl \
          title="CI watchdog · prettier auto-fix FAILED · MR !$CI_MR_IID" \
          action="bunx prettier --write . failed; see worktree $wt" \
          repo="$(basename "$TERMINAL_REPO")" \
          runId="${TERMINAL_RUN_ID:-}"
      fi
    )
    # Don't reap the worktree; keep for inspection if needed
    ;;

  test-real|build-config|deploy-infra|deploy-infra|dependency|lockfile-drift|ambiguous|"")
    # Not in the cheap-class allowlist — HITL the human
    terminal-cli mcp file_hitl \
      title="CI red · $classification · MR !$CI_MR_IID" \
      action="Pipeline $CI_PIPELINE_ID failed: $classification" \
      detail="Log: $log_file" \
      repo="$(basename "$TERMINAL_REPO")" \
      source="cron-fail" \
      runId="${TERMINAL_RUN_ID:-}"
    ;;

  eslint-fixable|typecheck-isolated|snapshot-mismatch)
    # On the "consider next" list — log as activity but HITL until allowlist
    # expansion lands.
    terminal-cli activity blocked \
      "CI watchdog · $classification (not allowlisted) · MR !$CI_MR_IID" \
      "in dry-run review queue — promote to auto-fix after a clean week"
    terminal-cli mcp file_hitl \
      title="CI red · $classification · MR !$CI_MR_IID" \
      action="Would be cheap to auto-fix once allowlist expands. Manual fix for now." \
      repo="$(basename "$TERMINAL_REPO")" \
      runId="${TERMINAL_RUN_ID:-}"
    ;;

  flake-network)
    # Transient — just note it, no HITL spam
    terminal-cli activity check \
      "CI flake detected · network · MR !$CI_MR_IID" \
      "transient; consider rerunning"
    ;;
esac
